apiVersion : apps/v1
kind: Deployment
metadata:
  name: "testskill"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "testskill"
  template:
    metadata:
      labels:
        app: "testskill"
    spec:
      containers:
        - name: "testskill"
          image: "heroes.azurecr.io/heroescluster"
          ports:
          - containerPort: 39783