apiVersion: v1
kind: Service
metadata:
    name: "testskill"
    labels:
        app: "testskill"
spec:
    ports:
    - port: 3978
      targetPort: 3978
      protocol: TCP
      name: http
    selector:
        app: "testskill"