apiVersion: v1
kind: Service
metadata:
    name: "testskill"
    labels:
        app: "testskill"
spec:
    ports:
    - port: 39783
      targetPort: 39783
      protocol: TCP
      name: http
    selector:
        app: "testskill"