apiVersion: v1
kind: Service
metadata:
    name: "testskill"
    labels:
        app: "testskill"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 39783
      protocol: TCP
      name: http
    selector:
        app: "testskill"